version: "3"
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./api:/app"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "147852369"
      MYSQL_PASSWORD: "147852369"
      MYSQL_USER: root
      MYSQL_DATABASE: cleanerino
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
